import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Header
import Header from "../components/page-layout/header";
// Font
const inter = Inter({ subsets: ["latin"] });
// Next utils
import { useMessages, NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export type Props = {
  children: React.ReactNode,
  params: {
    locale: "en" | "jp";
  }
}

const RootLayout: React.FC<Props> = ({
  children,
  params,
}: Props) => {
  const { locale } = params;
  const messages = useMessages();
  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </NextIntlClientProvider>
    </html>
  );
}

export default RootLayout